### ISSUE TITLE
Import as Module

### ISSUE THREAD

**Issue by bfillmer** [adrienjt/redux-data-structures#1]
<img width="1098" alt="screen shot 2017-07-27 at 6 50 09 pm" src="https://user-images.githubusercontent.com/33235/28697889-82934a92-72fc-11e7-98dd-350beb9b9c83.png">

Looks like when importing as a module `src/` is used and there is possibly some type of babel transformation plugin being used that I don't have in my project.

**Comment by adrienjt** [comment]
Thank you for creating this issue. You are correct: `transform-object-rest-spread` is required at this point. I'll babel-output an `es/` folder to improve compatibility.

**Comment by adrienjt** [comment]
Version 0.1.5 fixes your issue, replacing the object spread operator with `Object.assign` (commit 63a0fef).
