### ISSUE TITLE
Food for thought

### ISSUE THREAD

**Issue by hakunin** [adrienjt/redux-data-structures#2]
Hey guys,
I noticed this mentioned in a react newsletter and it looks similar to an approach I took with moving our app to redux.

Couple of things I didn't like about the default redux code found in tutorials:
- loads of uniquely named actions (ADD_TODO) as opposed to namespacing (<store>.ADD)
- non-reuse of reducers and constantly creating more of them

I came up with following solution:
- reducer factories (this is what you're doing)
- utilizing namespace and the same action names across same reducers, jus twith a different namespace (this is what redux already offers, but I don't see it used often enough)
- reducer factories create action trees (this is the food for thought)

Let me give you an example, with a singleton reducer (it just holds a value):

```
export default ((namespace, initial = null) => {
  const initialState = initial;
  var namespace;

  const handler = (state = initialState, action) => {
    const [action_namespace, action_type] = action.type.split('/');

    if (namespace != action_namespace) {
      return state;
    }

    switch (action_type) {
      case 'set':
        return action.payload;
      default:
        return state;
    }
  };

  let store;
  handler.__init = (_store, _namespace) => {
    store = _store;
    namespace = _namespace;
  };

  handler.__actions = {
    'set': (value) => {
      store.dispatch({
        type: namespace+'/set',
        payload: value
      });
    }
  };

  return handler;
});
```

Then I create the store like this:

```
import {
  createStore,
  combineReducers,
} from 'redux';

import {each} from 'lodash-es';
import {pluralize, camelize} from 'inflection';

import singletonReducer from '../reducers/singletonReducer';
import mapActions from './mapActions';


// This allows us to easily call actions on reducers, like so:
// Actions.task.set() and
const mapActions = (map, store, actions) => {

  // set actions for each store
  each(map, (v, k) => {
    if (v.__init) {
      v.__init(store, k);
      actions[k] = v.__actions;
    }
  });
};


const configureStore = (map, initialState = {}, actions = {}) => {
  const reducer = combineReducers(map);

  // pre-fill computer values
  initialState = wrappedReducer(initialState, {type: 'initComputed'});

  const store = createStore(
    reducer,
    initialState,
    window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
  );
  mapActions(map, store, actions);

  return store;
}

export default ({
  actions = {},
  state = window.__REDUX_INIT_CONTEXT,
} = {}) => {
  const map = {
    currentProjectId: singletonReducer(),
  };

  const store = configureStore(
    map,
    state,
    actions,
    globalReducers
  );

  return {
    redux: store,
    store: new Store(store, actions),
    actions: actions,
  };
};
```

Then I expose actions as `window.Actions`.

When I do that, I have a globally available map of actions, that is constructed by the reducers that I setup, so there is zero config, no need to remember or lookup action names.

Its all under `Actions.<reducer>.<action>(...)` and you can call it to dispatch action like that.

This is what I came up with in the first weeks and its super easy to use. You have far more experience so I bet you'll be able to come up with something smarter and cleaner if it inspires you.

**Comment by adrienjt** [comment]
Thank you for taking the time to share your approach. If it works for you and your team, then great! However, it deviates a lot from idiomatic Redux.
> Separation between actions and reducers is the whole reason Redux exists. (Dan Abramov)

On this topic, I recommend you read http://blog.isquaredsoftware.com/2017/05/idiomatic-redux-tao-of-redux-part-2/
