### ISSUE TITLE
Issue Building With Create React App

### ISSUE THREAD

**Issue by bfillmer** [adrienjt/redux-data-structures#4]
When using `redux-data-structures` in a Create React App based system development works fine. However when creating a production build using `yarn build` an UglifyJS error pops up:

<img width="776" alt="screen shot 2017-08-08 at 10 06 38 am" src="https://user-images.githubusercontent.com/33235/29081964-56e9c9f6-7c21-11e7-9536-dd7d1faf3061.png">

Looks like an issue with Uglification on the defaults set inside the function definitions.

Interestingly cloning the `redux-data-structures` repository into a sub-directory of `src` in the app, building it, and linking directly to `es6/index.js` works just fine for both development and production build.

**Comment by nickmccurdy** [comment]
I get the same with `npm run build` using `react-scripts@1.0.11`.

**Comment by adrienjt** [comment]
Sorry about that guys and thank you for your feedback.
I'll try a fix tomorrow.

**Comment by adrienjt** [comment]
UglifyJS doesn't support ES6, and Create React App and react-scripts haven't switched to Babel-Minify (Babili) yet. So I'd need to transpile even the `es/` export. Hopefully early next week I'll publish a fix for you guys. In the meantime, copy-pasting the library like @bfillmer did is the simplest workaround.
